// Generated by: zen link

import type { CoreDbSections } from "@zenbujs/core/registry-generated"
import type { SchemaRoot as AppRoot } from "../src/main/schema"

export type PluginDbSections = {
  app: AppRoot;
}

export type DbSections = CoreDbSections & PluginDbSections

export type DbRoot = { plugin: DbSections }
