// Generated by: zen link

import type { CoreEvents } from "@zenbujs/core/registry-generated"

/**
 * Intersection of every plugin's `Events` type. Plugins extend this
 * by declaring `events: "./path/to/events.ts"` in their
 * zenbu.plugin.json and exporting `export type Events = { ... }` from
 * that file. Each plugin chooses its own top-level namespace keys
 * (e.g. `pty`, `bottomTerminal`); colliding keys with different payload
 * shapes collapse to `never` at use sites — caught at compile time.
 */
export type PluginEvents = CoreEvents & Record<string, never>
