// Generated by: zen link

import type { CoreServiceRouter } from "@zenbujs/core/registry-generated"
import type { AppService } from "../src/main/services/app"
import type { Repo } from "../src/main/services/repo"

type ServiceBase =
  | "evaluate"
  | "shutdown"
  | "constructor"
  | "effect"
  | "__cleanupAllEffects"
  | "__effectCleanups"
  | "ctx"

type ExtractRpcMethods<T> = {
  [K in Exclude<keyof T, ServiceBase | `_${string}`> as T[K] extends (
    ...args: any[]
  ) => any
    ? K
    : never]: T[K]
}

export type PluginServiceRouter = {
  app: ExtractRpcMethods<AppService>;
  repo: ExtractRpcMethods<Repo>;
}

export type ServiceRouter = CoreServiceRouter & PluginServiceRouter
