// Generated by: zen link

import type {} from "@zenbujs/core/registry"
import type { DbRoot } from "./db-sections"
import type { ServiceRouter } from "./services"
import type { PluginEvents } from "./events"

declare module "@zenbujs/core/registry" {
  interface ZenbuRegister {
    db: DbRoot
    rpc: ServiceRouter
    events: PluginEvents
  }
}

export {}
